#!/bin/sh
proxy="http://proxy.noc.titech.ac.jp:3128/"
switch_triger="titech"

function set_proxy(){
   echo "switch to titech network"
   export HTTP_PROXY=$proxy
   export HTTPS_PROXY=$proxy
   export FTP_PROXY=$proxy
   export ALL_PROXY=$proxy

   git config --global http.proxy $proxy
   git config --global https.proxy $proxy
   git config --global url."https://".insteadOf git://
}

function unset_proxy(){
   echo "switch to automatic network"
   unset HTTP_PROXY
   unset HTTPS_PROXY
   unset FTP_PROXY
   unset ALL_PROXY

   git config --global --unset http.proxy
   git config --global --unset  https.proxy
   git config --global --unset url."https://".insteadOf
}

if [ "`networksetup -getcurrentlocation`" = "$switch_triger" ]; then
   set_proxy
else
   unset_proxy
fi

