#!/bin/zsh
TRASH_DIR=~/.Trash/

# skip options
while [[ $1 = -* ]]
do
    shift
done

# if no arguments, exit
if [ $# -eq 0 ]
then
    echo "usage: $0 file ..."
    exit 1
fi

for file in $@
dst_dir=$TRASH_DIR$(date +%Y%m%d-%H%M%S)
if [ -e dst_dir ]; then :
else
    mkdir -p "$dst_dir"
fi
mv -v $@ $dst_dir
